[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn freelance_platform.wsgi:application --bind 0.0.0.0:$PORT"